spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
  flyway:
    locations: classpath:db/migration
    validateOnMigrate: true
    cleanDisabled: true

logging:
  level:
    org.hibernate: warn

management:
  endpoints:
    web:
      exposure:
        include: loggers
