server:
  port: 4000

spring:
  datasource:
    url: ${DATASOURCE_MYSQL_URL:jdbc:mysql://mysql:3306/connexdatadb?serverTimezone=UTC&characterEncoding=UTF-8}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATASOURCE_MYSQL_USERNAME:gentlepeople}
    password: ${DATASOURCE_MYSQL_PASSWORD:0000}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    generate-ddl: false
  sql:
    init:
      mode: always
  flyway:
    enabled: true

logging:
  level:
    org.hibernate.sql: debug

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
