server:
  port: 4000

spring:
  datasource:
    url: ${DATASOURCE_MYSQL_URL:jdbc:mysql://localhost:3307/connexdatadb?serverTimezone=UTC&characterEncoding=UTF-8}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATASOURCE_MYSQL_USERNAME:gentlepeople}
    password: ${DATASOURCE_MYSQL_PASSWORD:gentlepeople}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  #   generate-ddl: false
  # sql:
  #   init:
  #     mode: always
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    #,classpath:db/callback
    baseline-version: 1721295672167
    # fail-on-missing-locations: true

logging:
  level:
    org.hibernate.sql: debug

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
