spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace
