version: '3.8'
name: connexdata

services:
  api:
    container_name: connexdata-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${SERVER_PORT}:8080'
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SERVER_PORT: 8080
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - $PWD/.env
    volumes:
      - ./src:/app/src
      - ./build:/app/build
      - ~/.gradle:/home/gradle/.gradle
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: connexdata-db
    image: mysql:8.1.0
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: 0000
      TZ: UTC
    env_file:
      - $PWD/.env
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - db-data:/var/lib/mysql
      - ./src/main/resources/db/migration/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
